name: Deploy to Staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}"" &> ~/ssh_key
          ssh -i  ~/ssh_key root@134.209.158.114
          cd typeracer-2/ && git pull 
          pnpm install 
          pnpm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server
